version: "3"
services:
  mongodb:
    image: mongo:5.0.14
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
  pacman-app: 
   image: pacman-app:007
   ports:
     - 8080:8080
   depends_on:
     - mongo-express