version: "3"
services:
  mongodb:
    image: mongo:5.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  # pacman:
  #   image: pacman-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGO_URL: mongodb://admin:password@mongodb:27017
