trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pacman-app'
  registry: 'pacmanrepo'
  dockerfilePath: './Dockerfile'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: $(registry)
    repository: $(imageName)
    command: build
    Dockerfile: $(dockerfilePath)

- task: Docker@2
  displayName: 'Start application in Docker container'
  inputs:
    containerRegistry: $(registry)
    repository: $(imageName)
    command: run
    ports: '8080:80'
    detach: true

- task: Docker@2
  displayName: 'Tag Docker image'
  inputs:
    containerRegistry: $(registry)
    repository: $(imageName)
    command: tag
    arguments: $(imageName):latest $(registry)/$(imageName):latest

- task: Docker@2
  displayName: 'Push Docker image to registry'
  inputs:
    containerRegistry: $(registry)
    repository: $(imageName)
    command: push
    Dockerfile: $(dockerfilePath)

