# Name der Pipeline
name: pacman-app-pipeline

# Definition der Trigger
trigger:
  - main

variables:
  imageName: 'pacman/pacman-app'
  registry: 'harbor'
  dockerfilePath: './Dockerfile'
  tag: 0.2 
  kubeconfig: 'K8s/kubeconfig.yaml' # Pfad zum Kubeconfig-File

# Build, push and Tag
steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(registry)
    tags: |
     $(tag)

# Deploy to K8s
- task: Kubernetes@1
  displayName: Deploy to Kubernetes
  inputs:
    connectionType: 'Kubernetes' # Verbindungstyp zu Kubernetes
    kubernetesServiceEndpoint: 'k8s connection' # Name Ihres Kubernetes-Service-Endpoints in Azure DevOps
    command: 'apply'
    useConfigurationFile: true
    configuration: 'K8s/deployment-pacman.yaml' # Pfad zum YAML-File für Kubernetes-Deployment
    secretType: 'kubeconfig'
    secretArguments: '-c $(kubeconfig)' # Pfad zur variable

# Install ansible
- script: |
    pip install ansible
    ansible --version
  displayName: 'Install Ansible'

#- script: sudo ansible-playbook -i ansible/inventory.ini ansible/pacmanplaybook.yml
#  displayName: 'Run Ansible Playbook'

# Füge den Ansible-Playbook-Schritt hinzu
- task: Ansible@4
  displayName: Run Ansible Playbook
  inputs:
    playbook: 'ansible/pacmanplaybook.yml' # Pfad zum Ansible-Playbook
    inventory: 'ansible/inventory.ini' # Ansible Inventory