# Name der Pipeline
name: pacman-app-pipeline

# Definition der Trigger
trigger:
  - main

variables:
  imageName: 'pacman/pacman-app'
  registry: 'harbor'
  dockerfilePath: './Dockerfile'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(registry)
    tags: |
      $(tag)
