apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
  namespace: tomvd-pac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman-app
  template:
    metadata:
      labels:
        app: pacman-app
    spec:
      containers:
      - name: pacman-app
        image: harbor.skyered-devops.de/pacman/pacman-app:0.2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets: 
        - name: harbor-login

